version: "3.9"
networks:
  leantime:
    external: false
    driver: bridge
volumes:
  mysql:

services:
  leantime-dev:
    privileged: true
    build: .
    ports:
      - "8090:8080"
    volumes:
      - "../:/var/www/html"
      - "./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini"
      - ${PWD}/test.env:/var/www/html/config/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - leantime
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: leantime
      MYSQL_USER: leantime
      MYSQL_PASSWORD: leantime
      MYSQL_DATABASE: leantime_test
    networks:
      - leantime
    volumes:
      - mysql:/var/lib/mysql:rw
    healthcheck:
      test: "mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1'"
      interval: 5s
      timeout: 5s
      retries: 20
